# Describe Capital IQ Transcripts Tables Available in WRDS

In [1]:
import config
import wrds
import pandas as pd

conn = wrds.Connection(wrds_username=config.WRDS_USERNAME, password=config.WRDS_PASSWORD)
ciq_tables = conn.list_tables(library='ciq')
transcript_tables = [table for table in ciq_tables if 'transcript' in table]

Loading library list...

Done

## Table names and stats

In [2]:
ciq_table_stats = []

for table in transcript_tables:
    query = f"SELECT * FROM ciq.{table} LIMIT 1"
    df = conn.raw_sql(query)
    nrow = conn.get_row_count(library='ciq', table=table)
    ncol = len(df.columns)
    size_gb = df.memory_usage(deep=True).sum() * nrow / (1024 ** 3)
    col_names = df.columns.tolist()
    
    ciq_table_stats.append({
        'name': table,
        'nrow': nrow,
        'ncol': ncol,
        'size_gb': size_gb,
        'col_names': col_names
    })

ciq_table_stats = pd.DataFrame(ciq_table_stats)
ciq_table_stats

,name,nrow,ncol,size_gb,col_names
0,ciqtranscript,1592151,6,2.906300e-01,"[keydevid, transcriptid, transcriptcollectiont..."
1,ciqtranscriptcollectiontype,9,2,1.684763e-06,"[transcriptcollectiontypeid, transcriptcollect..."
2,ciqtranscriptcomponent,84218632,6,9.529818e+02,"[transcriptcomponentid, transcriptid, componen..."
3,ciqtranscriptcomponenttype,8,2,1.624227e-06,"[transcriptcomponenttypeid, transcriptcomponen..."
4,ciqtranscriptdelayreason,34704,5,6.593406e-03,"[keydevid, mostimportantdateutc, delayreasonty..."
5,ciqtranscriptdelayreasontype,19,3,3.751367e-06,"[delayreasontypeid, delayreasontypename, iscan..."
6,ciqtranscriptperson,511261,5,1.204657e-01,"[transcriptpersonid, transcriptpersonname, pro..."
7,ciqtranscriptpresentationtype,2,2,3.725290e-07,"[transcriptpresentationtypeid, transcriptprese..."
8,ciqtranscriptspeakertype,5,2,9.173527e-07,"[speakertypeid, speakertypename]"
9,wrds_transcript_detail,1624946,16,8.383953e-01,"[companyid, keydevid, transcriptid, headline, ..."
10,wrds_transcript_person,84015664,13,5.711935e+01,"[transcriptid, transcriptcomponentid, componen..."

## List variables

In [3]:
for index, row in ciq_table_stats.iterrows():
    print(f"Table: {row['name']}")
    print("Columns:")
    for col in row['col_names']:
        print(f" - {col}")
    print("\n")

Table: ciqtranscript
Columns:
 - keydevid
 - transcriptid
 - transcriptcollectiontypeid
 - transcriptpresentationtypeid
 - transcriptcreationdateutc
 - audiolengthsec


Table: ciqtranscriptcollectiontype
Columns:
 - transcriptcollectiontypeid
 - transcriptcollectiontypename


Table: ciqtranscriptcomponent
Columns:
 - transcriptcomponentid
 - transcriptid
 - componentorder
 - transcriptcomponenttypeid
 - transcriptpersonid
 - componenttext


Table: ciqtranscriptcomponenttype
Columns:
 - transcriptcomponenttypeid
 - transcriptcomponenttypename


Table: ciqtranscriptdelayreason
Columns:
 - keydevid
 - mostimportantdateutc
 - delayreasontypeid
 - newdateutc
 - delayreasonnotes


Table: ciqtranscriptdelayreasontype
Columns:
 - delayreasontypeid
 - delayreasontypename
 - iscancelledflag


Table: ciqtranscriptperson
Columns:
 - transcriptpersonid
 - transcriptpersonname
 - proid
 - companyname
 - speakertypeid


Table: ciqtranscriptpresentationtype
Columns:
 - transcriptpresentationtypeid
 - transcriptpresentationtypename


Table: ciqtranscriptspeakertype
Columns:
 - speakertypeid
 - speakertypename


Table: wrds_transcript_detail
Columns:
 - companyid
 - keydevid
 - transcriptid
 - headline
 - mostimportantdateutc
 - mostimportanttimeutc
 - keydeveventtypeid
 - keydeveventtypename
 - companyname
 - transcriptcollectiontypeid
 - transcriptcollectiontypename
 - transcriptpresentationtypeid
 - transcriptpresentationtypename
 - transcriptcreationdate_utc
 - transcriptcreationtime_utc
 - audiolengthsec


Table: wrds_transcript_person
Columns:
 - transcriptid
 - transcriptcomponentid
 - componentorder
 - transcriptcomponenttypeid
 - transcriptcomponenttypename
 - transcriptpersonid
 - transcriptpersonname
 - proid
 - companyofperson
 - speakertypeid
 - speakertypename
 - componenttextpreview
 - word_count

## Head of main table
wrds_transcript_detail

In [4]:
transcript_heads = {}
for table in transcript_tables:
    query = f"SELECT * FROM ciq.{table} LIMIT 5"
    df = conn.raw_sql(query)
    transcript_heads[table] = df.head()

transcript_heads['wrds_transcript_detail']

,companyid,keydevid,transcriptid,headline,mostimportantdateutc,mostimportanttimeutc,keydeveventtypeid,keydeveventtypename,companyname,transcriptcollectiontypeid,transcriptcollectiontypename,transcriptpresentationtypeid,transcriptpresentationtypename,transcriptcreationdate_utc,transcriptcreationtime_utc,audiolengthsec
0,NaN,1.888144e+09,3214308.0,None,None,None,NaN,None,None,7,Spellchecked Copy,4,Preliminary,2024-08-06,17:06:26,3865.0
1,NaN,1.888144e+09,3214327.0,None,None,None,NaN,None,None,7,Spellchecked Copy,4,Preliminary,2024-08-06,17:19:28,3865.0
2,NaN,1.888144e+09,3214420.0,None,None,None,NaN,None,None,2,Edited Copy,5,Final,2024-08-06,18:10:32,3865.0
3,18511.0,1.156484e+08,93162.0,"3i Group plc, H1 2011 Earnings Call, Nov 11, 2010",2010-11-11,09:45:00,48.0,Earnings Calls,3i Group plc,7,Spellchecked Copy,4,Preliminary,2011-01-20,20:21:55,2945.0
4,18511.0,1.156484e+08,93403.0,"3i Group plc, H1 2011 Earnings Call, Nov 11, 2010",2010-11-11,09:45:00,48.0,Earnings Calls,3i Group plc,2,Edited Copy,5,Final,2011-01-21,00:22:45,2945.0

In [5]:
conn.close()